name: Build and Deploy Dataflow r365 jobs

on:
  push:
    branches:
      - main
    paths:
      - 'dataflow/**.py'
      - '.github/workflows/dataflow_*.yml'
      - 'dataflow/common/**'
      - 'dataflow/requirements.txt'

jobs:
  run-prebuildings:
    if: >
      ${{ github.event_name == 'push' &&
           contains(github.event.paths, 'dataflow/common/') &&
           contains(github.event.paths, 'dataflow/requirements.txt') &&
           contains(github.event.paths, '.github/workflows/dataflow_prebuildings.yml') }}
    uses: ./.github/workflows/dataflow_prebuildings.yml
    name: Build Prebuilding
    secrets: inherit
  build-push-deploy:
    needs: run-prebuildings
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: district-brands-production
      REGION: us-east1
      REF_NAME: ${{github.ref_name}}
      STAGING_LOCATION: gs://dt-etls/dataflow/staging/
      TEMP_LOCATION: gs://dt-etls/dataflow/temp/
      SA_DF: dataflow-sa@district-brands-production.iam.gserviceaccount.com
      DATAFLOW_REPO: dataflow-prebuildings
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4 

    - name: 'Authenticate with Cloud SDK'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'beta'

    - name: Install Requirements for dataflow template
      run: |-
        python3 -m venv dataflow/.venv
        source dataflow/.venv/bin/activate && pip install --upgrade pip
        pip install -r dataflow/requirements.txt