name: Build Prebuild Image for Dataflow

on:
  workflow_call:
  
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: factored-hackaton-2024
      REGION: us-east1
      REF_NAME: ${{github.ref_name}}
      DATAFLOW_REPO: dataflow-prebuildings
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 'Authenticate with Cloud SDK'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'beta'

    - name: 'Configure registry'
      run: |-
        gcloud auth configure-docker $REGION-docker.pkg.dev
        REF_NAME=${REF_NAME//_/-}
        echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV

    - name: Build and export to Cloud Artifact Registry
      uses: docker/build-push-action@v2
      with:
        context: ./dataflow/
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DATAFLOW_REPO }}/${{ env.REF_NAME }}:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max