name: Daily GDELT GKG Extract

on:
  schedule:
    - cron: '15 0 * * *'  # Runs at 12:15 AM UTC every day

jobs:
  run-dataflow-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: factored-hackaton-2024
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Get yesterday's date
      id: get_date
      run: echo "YESTERDAY=$(date -d 'yesterday' +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Run Dataflow job
      run: |
        gcloud dataflow jobs run gdelt_gkg_extract_2024_1 \
          --project factored-hackaton-2024 \
          --gcs-location "gs://factored-hackaton-2024/dataflow/templates/gdelt_gkg_extract_main" \
          --region us-east1 \
          --service-account-email github-cicd@factored-hackaton-2024.iam.gserviceaccount.com \
          --worker-machine-type n1-standard-4 \
          --parameters start_date="${{ steps.get_date.outputs.YESTERDAY }}" \
          --parameters end_date="${{ steps.get_date.outputs.YESTERDAY }}" \
          --max-workers 4