name: On-demand GDELT GKG Extract

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End date (YYYY-MM-DD, optional)'
        required: false

jobs:
  run-dataflow-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: factored-hackaton-2024
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Set end date
      run: echo "END_DATE=${{ github.event.inputs.end_date || github.event.inputs.start_date }}" >> $GITHUB_ENV

    - name: Run Dataflow job
      run: |
        gcloud dataflow jobs run gdelt_gkg_extract_2024_1 \
          --project factored-hackaton-2024 \
          --gcs-location "gs://factored-hackaton-2024/dataflow/templates/gdelt_gkg_extract_main" \
          --region us-east1 \
          --service-account-email github-cicd@factored-hackaton-2024.iam.gserviceaccount.com \
          --worker-machine-type n1-standard-4 \
          --parameters start_date="${{ github.event.inputs.start_date }}" \
          --parameters end_date="${{ env.END_DATE }}" \
          --max-workers 4